#!/bin/sh

pip3 install -r /srv/reversed/backend/requirements.txt
pip3 install -r /srv/reversed/serial-reader/requirements.txt

sudo patch -f /etc/redis/redis.conf < /tmp/redis.conf.patch

rm /etc/nginx/sites-enabled/default

sudo systemctl enable redis
sudo systemctl enable reversed-backend
sudo systemctl enable reversed-serial-reader

sudo systemctl start redis
sudo systemctl start reversed-backend
sudo systemctl start reversed-serial-reader
