#!/bin/sh
pip3 install wheel
pip3 install -r /srv/reversed/backend/requirements.txt
pip3 install -r /srv/reversed/serial-reader/requirements.txt

patch -f /etc/redis/redis.conf < /tmp/redis.conf.patch

rm /etc/nginx/sites-enabled/default

systemctl enable redis
systemctl enable reversed-backend
systemctl enable reversed-serial-reader

systemctl start redis
systemctl start reversed-backend
systemctl start reversed-serial-reader
